#ifneq ($(KERNELRELEASE),)
#	obj-m += lego.o
#else
#
#KDIR ?= /lib/modules/$$(uname -r)/build
#
#all:
#	$(MAKE) -C $(KDIR) M=$$PWD modules
#
#clean:
#	$(MAKE) -C $(KDIR) M=$$PWD clean
#
#.PHONY  : clean
#endif
