#
# Lego Memory Component
#

obj-y := core.o
obj-y += gpid.o
obj-y += handle_fork.o
obj-y += handle_execve.o
obj-y += handle_mmap.o
obj-y += handle_file.o
obj-y += handle_checkpoint.o
obj-y += file_ops.o
obj-y += missing_syscalls.o
obj-y += m2s_read_write.o

# Pcache
obj-y += pcache/

# Virtual Memory Subsystem
obj-y += vm/

# Loader
obj-y += loader/

obj-y += ramfs/
