#
# Lego Memory Component
#

obj-y := core.o
obj-y += gpid.o
obj-y += handle_fork.o
obj-y += handle_pcache.o
obj-y += handle_execve.o
obj-y += handle_mmap.o
obj-y += handle_file.o
obj-y += file_ops.o
obj-y += missing_syscalls.o

# Virtual Memory Subsystem
obj-y += vm/

# Loader
obj-y += loader/

obj-y += ramfs/
