#
# Makefile for Lego core functionalities
#

obj-y := panic.o
obj-y += printk.o
obj-y += kallsyms.o
obj-y += cpu.o
obj-y += resource.o
obj-y += smp.o
obj-y += param.o
obj-y += time/
obj-y += irq/
obj-y += sched/
obj-y += fork.o
obj-y += pid.o
