#
# Libraries: used by core-kernel
#

obj-y := vsprintf.o
obj-y += ctype.o
obj-y += hexdump.o
obj-y += string.o
obj-y += sort.o
obj-y += find_bit.o
obj-y += bitmap.o
obj-y += hweight.o
obj-y += rbtree.o
obj-y += scatterlist.o
obj-y += bcd.o
obj-y += cpumask.o
obj-y += cmdline.o
obj-y += strncpy_from_user.o
obj-y += strnlen_user.o
obj-y += plist.o
obj-y += dump_task_struct.o
obj-y += ratelimit.o
obj-y += kstrtox.o
obj-y += random.o
obj-y += sched.o
obj-y += dump_remote_cpustack.o
obj-y += radix-tree.o
