#
# Makefile for Lego Scheduler
#

obj-y := core.o
obj-y += wait.o
obj-y += idle.o
obj-y += completion.o
obj-y += cputime.o
obj-y += debug.o
obj-y += task_stop.o task_rt.o task_dl.o task_fair.o task_idle.o
