#
# LegoOS Memory Managment
#

obj-y := slab.o
obj-y += debug.o
obj-y += memory.o
obj-y += sparse.o sparse-vmemmap.o
obj-y += init-mm.o
obj-y += vmalloc.o
obj-y += memblock.o
obj-y += page_alloc.o
obj-y += early_ioremap.o
