# General Clockevent Infrastructure
obj-y := clocksource.o
obj-y += clockevents.o

obj-y += jiffies.o
obj-y += time.o
obj-y += timekeeping.o
obj-y += timer.o
obj-y += posix-timers.o
obj-y += ntp.o

# Genetic Timer Interrupt Handler
obj-y += tick-common.o
