#
# Filesystem Interfaces in Lego Processor Manager
#

obj-y := read_write.o
obj-y += open.o
obj-y += stat.o
obj-y += fcntl.o
obj-y += ioctl.o
obj-y += stdio.o
obj-y += normal_ops.o

#
# To maintain compability with linux
#
obj-y += seq_file.o
obj-y += proc/
obj-y += sys/
obj-y += dev/
