#
# Makefile for Lego processor-component manager
#

obj-y := core.o
obj-y += fork.o
obj-y += exec.o
obj-y += pgtable.o
obj-y += wait.o
obj-y += mmap/
obj-y += pcache/
obj-y += fs/
obj-y += monitor/
obj-$(CONFIG_CHECKPOINT) += checkpoint/
